### ISSUE TITLE
It is not possible to save data in confocal (the three image plots) via right click and export 

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#101]
Migration: trac#250.

    ValueError?: max() arg is an empty sequence

    Traceback (most recent call last):
    File "C:\Users\Quantum Optics\Anaconda3\lib\site-packages\pyqtgraph\exporters\Exporter.py", line 77, in fileSaveFinished
        self.export(fileName=fileName, self.fileDialog.opts)

    File "C:\Users\Quantum Optics\Anaconda3\lib\site-packages\pyqtgraph\exporters\CSVExporter.py", line 62, in export
        numRows = max([len(d[0]) for d in data])

**Comment by drogenlied** [comment]
Just for clarification:
It seems that this only a problem if you want to export 3D data in csv format. For all the 2d data plots it works fine.

Therefore all xy, xz, ... scans will suffer from that error. However, you can still use all the other save functions. The problem is most probably an error in the csv exporter of the pyqtgraph package.

**Comment by drogenlied** [comment]
According to the PyQtGraph? documentation, this feature is not completely supported for 3D data:

​http://www.pyqtgraph.org/documentation/exporting.html#exporting-3d-graphics

It looks like that simply the implementation is missing.
