### ISSUE TITLE
Logger produces exceptions on some installation

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#102]
Migration: trac#253.

I encounter an error when launching start.py and was wondering if
you could perhaps shed some light on it.

I'm running Debian, have created a python 3 virtual environment, and
have installed all of the required packaged excluding pythonnet (as
much as I have tried I have not yet been able to install this,
however I do not believe that it is contributing to the current
problem), and also any packages listed in
tools/debian-jessie-pip.txt. I've cloned the QuDi? repository
straight from GitHub? and not modified anything.

From inside the virtual environment, I run start.py. I then receive
the following error, which seams to be originating from logger.py:

    TypeError?: emit() takes 2 positional arguments but 3 were given

The complete traceback in the terminal is copied to the end of this email.

My feeling is that all the packages required to launch start.py are
installed fine, but the function emit() withing logger.py that is
having an unhappy time.

I greatly appreciate any insight you could provide into this problem.

    Traceback (most recent call last):

        File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main

            "main", mod_spec)

        File "/usr/lib/python3.4/runpy.py", line 85, in _run_code

            exec(code, run_globals)

        File "/media/mvb/Disk2/QuDi/qudi_clone/core/main.py", line

    59, in <module>
    logger.info('Loading QuDi?...')

        File "/usr/lib/python3.4/logging/init.py", line 1274, in info

    self._log(INFO, msg, args, kwargs)

        File "/usr/lib/python3.4/logging/init.py", line 1409, in _log

    self.handle(record)

        File "/usr/lib/python3.4/logging/init.py", line 1419, in handle

    self.callHandlers(record)

        File "/usr/lib/python3.4/logging/init.py", line 1481, in

    callHandlers
    hdlr.handle(record)

        File "/usr/lib/python3.4/logging/init.py", line 853, in handle

    self.emit(record)

        File "/media/mvb/Disk2/QuDi/qudi_clone/core/logger.py", line 111,

    in emit

            if record: self.sigLoggedMessage.emit(record)

    TypeError?: emit() takes 2 positional arguments but 3 were given
    Unexpected return value 1. Exiting.
    Traceback (most recent call last):

        File "start.py", line 70, in <module>

    sys.exit(retval)
    SystemExit?: 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):

        File "start.py", line 75, in <module>

    process.kill()

        File "/usr/lib/python3.4/subprocess.py", line 1691, in kill

    self.send_signal(signal.SIGKILL)

        File "/usr/lib/python3.4/subprocess.py", line 1681, in send_signal

    os.kill(self.pid, sig)
    ProcessLookupError?: [Errno 3] No such process

Just shooting through an update. I can now launch QuDi? after changing
the following:

    core/logger.py line#111 to if record: pass

commenting out line#59 in main.py.

**Comment by drogenlied** [comment]
This is a PySide issue.
PySide is not supported right now.
Probably related to the different method resolution order (MRO) when using PySide.
