### ISSUE TITLE
Optimizer: does not unlock after fit fails

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#161]
Discovered with #160 on bbranch qt5-migration.

```
Traceback (most recent call last):
  File "/home/jan/qo/qudi/logic/optimizer_logic.py", line 277, in start_refocus
    scanner_status = self.start_scanner()
  File "/home/jan/qo/qudi/logic/optimizer_logic.py", line 622, in start_scanner
    self.lock()
  File "/home/jan/miniconda/envs/qudi/lib/python3.6/site-packages/fysom/__init__.py", line 261, in fn
    "event %s inappropriate in current state %s" % (event, self.current))
fysom.FysomError: event lock inappropriate in current state locked
```

**Comment by Neverhorst** [comment]
I think this has been resolved long ago. Now the optimizer is throwing an error if the fit fails but unlocks afterwards.
