### ISSUE TITLE
Fit names were changed but not updated in pulsed_measurement_logic

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#162]
Produces the following error on the qt5-migration branch:
```
Failed to validate fit Lorentzian dip
Traceback (most recent call last):
  File "/home/jan/qo/qudi/logic/fit_logic.py", line 201, in validate_load_fits
    new_fit['make_fit'] = self.fit_list[dim][fname]['make_fit']
KeyError: 'lorentzoffset'
Failed to validate fit Two Lorentzian dips
Traceback (most recent call last):
  File "/home/jan/qo/qudi/logic/fit_logic.py", line 201, in validate_load_fits
    new_fit['make_fit'] = self.fit_list[dim][fname]['make_fit']

```

**Comment by Neverhorst** [comment]
Removed the default fits until the concept for the fit_logic stands and is consequently enforced. No error anymore.
