### ISSUE TITLE
Crosshair jumps when resizing the scan range

### ISSUE THREAD

**Issue by a-stark** [Ulm-IQO/qudi#388]
## *What* is affected by this bug?

The crosshair jumps (if it is not within the scan range) during the confocal scan, and jumps back to its initial position.

## *When* does this occur?

This happened during the test of #378 .

## *Where* on the platform does it happen?

Windows 10, 64bit, Version 1803, Build 17134.112

## *How* do we replicate the issue?

- the example configuration is used fo the confocal scanning (GUI and logic + confocal scanner dummy)
- Open confocal GUI and set the scan range to max (e.g. 100um). Put the cursor in the middle (I consider here the xy image).
- Decrease now the x_max and y_max values by a factor of 3 (so that the cursor lays not inside the new scan picture).
- Press scan: The cursor moves to the corner of the picture (this is ok)
- When the scan stops/finishes the cursor jumps back to its initial position.

## Expected behavior (i.e. solution)

Something is not consistent here, either the crosshair stays were it was before (also during the scan) or the crosshair stays at the corner of the new scan.

## Screenshots:
During scan:
![grafik](https://user-images.githubusercontent.com/18192374/41725251-a2fda5ae-756f-11e8-9a6e-79a286042bcd.png)

After scan ended:
![grafik](https://user-images.githubusercontent.com/18192374/41725298-bbb36a0c-756f-11e8-878c-98d72d4d37bf.png)

**Comment by diamond2nv** [comment]
Run on actural PZT E-727 P-563.

Bug:
 * When Confocal GUI started , confocal_logic init function will first send stage move to the middles of xyz range, it can be dangerous for the object lens (z axis).

Module:
- [ ] confocal_logic.py

ToFix
- [ ] Add a way to set ini_position as init PZT stage position in the config, if gui cannot get position in time from logic or hardware or history.

--- add raise to send position to find out:
```python
Error during activation
RuntimeError: No active exception to reraise
Traceback (most recent call last):
...
  File "\qudi\logic\confocal_logic.py", line 345, in on_activate
    self._change_position('activation')

  File "\qudi\logic\confocal_logic.py", line 687, in _change_position
    self._scanning_device.scanner_set_position(**pos_dict)

  File "\qudi\logic\interfuse\confocal_scanner_motor_interfuse.py", line 220, in scanner_set_position
    raise
```
