### ISSUE TITLE
PR #458 breaks when using analog laser channel / analog-only AWG

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#465]
## *What* is affected by this bug?

Win10 Build 1803, Qudi form master branch, pulsed with all-analog AWG (M3202).

## *When* does this occur / How to replicate?

Adding a pulse block to a pulse block ensemble while using an AWG without digital channels or while using an analog laser channel.

## *Where* on the platform does it happen?

```
Traceback (most recent call last):
  File "C:\Software\qudi\gui\pulsed\pulsed_maingui.py", line 1723, in editor_generate_ensemble_clicked
    length_s, length_bins, lasers = self.pulsedmasterlogic().get_ensemble_info(ensemble_object)
  File "C:\Software\qudi\logic\pulsed\pulsed_master_logic.py", line 970, in get_ensemble_info
    return self.sequencegeneratorlogic().get_ensemble_info(ensemble=ensemble)
  File "C:\Software\qudi\logic\pulsed\sequence_generator_logic.py", line 1062, in get_ensemble_info
    ens_lasers = len(info_dict['digital_rising_bins'][laser_channel])
KeyError: 'a_ch1'
```

## Expected behavior (i.e. solution)

Laser should be considered on if analog channel != 0.

## Other Comments
Yo.

**Comment by kay-jahnke** [comment]
resolved by #473
