### ISSUE TITLE
Instreamer crush when trying to stop slow counter with APD off.

### ISSUE THREAD

**Issue by meiwud334** [Ulm-IQO/qudi#627]
## instreamer error when trying to stop slow counter with no data streaming in.

Traceback (most recent call last):
  File "C:\software\qudi_n\hardware\ni_x_series_in_streamer.py", line 1085, in terminate_all_tasks
    if not self._di_task_handles[i].is_task_done():
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\software\qudi_n\logic\time_series_reader_logic.py", line 544, in acquire_data_block
    if self._streamer.stop_stream() < 0:
  File "C:\software\qudi_n\hardware\ni_x_series_in_streamer.py", line 607, in stop_stream
    self.terminate_all_tasks()
  File "C:\software\qudi_n\hardware\ni_x_series_in_streamer.py", line 1092, in terminate_all_tasks
    del self._di_task_handles[i]
IndexError: list assignment index out of range

## *When* does this occur?
When try to stop the slow counter with APD off/ no data streaming in

## *Where* on the platform does it happen?
Windows 8.1 Enterprise

## *How* do we replicate the issue?
Stop the slow counter when there is no data coming in.

## Expected behavior (i.e. solution)
The gui of time serie will freeze, because of error mentioned above from instreamer.

**Comment by Neverhorst** [comment]
Fixed by PR #645
