### ISSUE TITLE
Python crashed after clicking "delete last point" in POI Manager

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#90]
Migration: trac#210.

2016.06.30 14:06:09

    Traceback (most recent call last):

    File "C:\software\qudi\logic\poi_manager_logic.py", line 646, in _refocus_done

    Fatal Python error: Segmentation fault

    Thread 0x00000dac (most recent call first):

    File "C:\Anaconda3\envs\qudi\lib\site-packages\pyqtgraph\exceptionHandling.py", line 67 in call

    Thread 0x00001590 (most recent call first):

    File "C:\Anaconda3\envs\qudi\lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 25 in mafunction
    File "<string>", line 2 in function
    File "C:\software\qudi\hardware\ni_card.py", line 721 in get_counter
    File "C:\software\qudi\logic\counter_logic.py", line 478 in countLoopBody_continuous

    Thread 0x00001658 (most recent call first):

    File "C:\software\qudi\core\parentpoller.py", line 122 in run
    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 911 in _bootstrap_inner
    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 879 in _bootstrap

    Thread 0x00001450 (most recent call first):

    File "C:\Anaconda3\envs\qudi\lib\site-packages\zmq\utils\garbage.py", line 47 in run
    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 911 in _bootstrap_inner
    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 879 in _bootstrap

    Thread 0x00001b3c (most recent call first):

    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 290 in wait
    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 546 in wait
    File "C:\Anaconda3\envs\qudi\lib\site-packages\IPython\core\history.py", line 798 in run
    File "C:\Anaconda3\envs\qudi\lib\site-packages\IPython\core\history.py", line 68 in needs_sqlite
    File "<decorator-gen-23>", line 2 in run
    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 911 in _bootstrap_inner
    File "C:\Anaconda3\envs\qudi\lib\threading.py", line 879 in _bootstrap

    Thread 0x00001940 (most recent call first):

    File "C:\Anaconda3\envs\qudi\lib\socket.py", line 187 in accept
    File "C:\Anaconda3\envs\qudi\lib\site-packages\rpyc\utils\server.py", line 128 in accept
    File "C:\Anaconda3\envs\qudi\lib\site-packages\rpyc\utils\server.py", line 241 in start
    File "C:\software\qudi\core\remote.py", line 184 in run

    Current thread 0x000020b8 (most recent call first):

    File "C:\Anaconda3\envs\qudi\lib\site-packages\numpy\core\fromnumeric.py", line 48 in _wrapit
    File "C:\Anaconda3\envs\qudi\lib\site-packages\numpy\core\fromnumeric.py", line 1733 in clip
    File "C:\Anaconda3\envs\qudi\lib\site-packages\pyqtgraph\graphicsItems\ViewBox?\ViewBox?.py", line 642 in suggestPadding
    File "C:\Anaconda3\envs\qudi\lib\site-packages\pyqtgraph\graphicsItems\ViewBox?\ViewBox?.py", line 896 in updateAutoRange
    File "C:\Anaconda3\envs\qudi\lib\site-packages\pyqtgraph\graphicsItems\ViewBox?\ViewBox?.py", line 298 in prepareForPaint
    File "C:\Anaconda3\envs\qudi\lib\site-packages\pyqtgraph\GraphicsScene?\GraphicsScene?.py", line 115 in prepareForPaint
    File "C:\Anaconda3\envs\qudi\lib\site-packages\pyqtgraph\widgets\GraphicsView?.py", line 153 in paintEvent
    File "C:\software\qudi\core\main.py", line 226 in <module>
    File "C:\Anaconda3\envs\qudi\lib\runpy.py", line 85 in _run_code
    File "C:\Anaconda3\envs\qudi\lib\runpy.py", line 170 in _run_module_as_main

    Unexpected return value 3221225477. Exiting.

    Process finished with exit code -1

**Comment by Neverhorst** [comment]
Obsolete since POI manager has been revised
