### ISSUE TITLE
Error while refinding POI

### ISSUE THREAD

**Issue by drogenlied** [Ulm-IQO/qudi#94]
Migration: trac#217.

When trying to refind a POI without ticking the option Crosshair follows POI, this error happens

Error Log:

    Unexpected error:
    ValueError?: operands could not be broadcast together with shapes (3,) (0,)

    Traceback (most recent call last):

    File "C:\software\qudi\logic\poi_manager_logic.py", line 643, in _refocus_done

        self.go_to_poi(poikey='crosshair')

    File "C:\software\qudi\logic\poi_manager_logic.py", line 385, in go_to_poi

        x, y, z = self.get_poi_position(poikey=poikey)

    File "C:\software\qudi\logic\poi_manager_logic.py", line 409, in get_poi_position

        return sample_pos + poi_coords

**Comment by Neverhorst** [comment]
obsolete since POI manager has been revised
